AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: AWS Cognito-identity template
Parameters:
  AppName:
    Type: String
    Description: App name to be used for as a prefix for resources for this app
    Default: 'example-serverless-di'

Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 180

###############
## Resources ##
###############
Resources:
  PostCustomerOrders:
    Type: AWS::Serverless:Function
    Properties:
      CodeUri: ./main
      DefinitionUri: bundle.PostCustomerOrders
