package(default_visibility = ["//visibility:public"])
exports_files(["tsconfig.json"])
# load("@npm_bazel_typescript//:index.bzl", "ts_library")

# ts_library(
#     name = "library",
#     srcs = glob(
#         [
#             "common/**/*.ts",
#             "core/**/*.ts",
#             "index.ts",
#         ],
#         exclude = [
#             "*.test.ts",
#             "*.spec.ts",
#             "*.e2e.ts",
#         ],
#     ),
#     module_name = "@serverless-di",
#     deps = [
#         "//serverless-di/main/common:library",
#         "//serverless-di/main/core:library",
#         "@npm//@types/node",
#         "@npm//inversify",
#         "@npm//reflect-metadata",
#     ],
# )
