export enum EventSource {
  CloudFront = 'isCloudfront',
  AwsConfig = 'isAwsConfig',
  CodeCommit = 'isCodeCommit',
  ApiGatewayAuthorizer = 'isApiGatewayAuthorizer',
  CloudFormation = 'isApiGatewayAuthorizer',
  Ses = 'isSes',
  ApiGatewayAwsProxy = 'isApiGatewayAwsProxy',
  ScheduledEvent = 'isScheduledEvent',
  CloudWatchLogs = 'isCloudWatchLogs',
  Sns = 'isSns',
  DynamoDb = 'isDynamoDb',
  KinesisFirehose = 'isKinesisFirehose',
  CognitoSyncTrigger = 'isCognitoSyncTrigger',
  Kinesis = 'isKinesis',
  S3 = 'isS3',
  MobileBackend = 'isMobileBackend',
  Custom = 'isCustom',
}
